# as of https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905,
# here is a sample config for py37
language: python
sudo: required
dist: xeniall
python:
  - "3.7"
script:
  - pytest
