package: 
  name: buyrandom
  version: 0.1.2

source:
  git_url: https://github.com/tngTUDOR/buyrandom.git

requirements:
  build:
      - python
      - setuptools
  run:
      - python
      - docopt
      - appdirs

about:
  home: https://github.com/tngTUDOR/buyrandom
  #license: BSD
  #license_file: LICENSE.txt

build:
  entry_points:
    - buyrandom-cli = buyrandom.bin.buyrandom_cli:main

